typography_spectrum: 0.9600851670838892
color:
  brandStrength: 0.4928040155209601
  lightness: 0.17314560594968498
  saturation: 0.8764619550202042
  rhythmicContrast: 0.4336446668021381
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.24790062196552753
name: Jonathan Reiswig
title: Jonathan Reiswig
description: Actor
